import "oaidl.idl";
import "ocidl.idl";
import "mwcomtypes.idl";

[
  object,
  uuid("7E226D48-2672-458E-8202-0F04B12D9771"),
  dual,
  helpstring("IClass1 Interface"),
  pointer_default(unique)
]
interface IClass1 : IDispatch
{
  [propget, id(1), helpstring("property MWFlags")]
  HRESULT MWFlags([out, retval] IMWFlags** ppvFlags);
  [propput, id(1), helpstring("property MWFlags")]
  HRESULT MWFlags([in] IMWFlags* pvFlags);

  [id(2), helpstring("Method steelfault")]
  HRESULT steelfault([in] long nargout, [in,out] VARIANT* out, [in] VARIANT in);

  [propget, id(3), helpstring("property help")]
  HRESULT help([in] BSTR funcname, [out, retval] BSTR* helptext);

};
[
  uuid("77F3BA5C-D6C3-45C1-BCAC-98641724ABCE"),
  version(1.0),
  helpstring("fault_detect 1.0 Type Library")
]
library fault_detect
{
  importlib("stdole32.tlb");
  importlib("stdole2.tlb");
  importlib("mwcomutil.tlb");

  [
    uuid("CB1EBE8D-E218-4CC1-BB12-C42FDB0283B8"),
    helpstring("Class1 Class")
  ]
  coclass Class1
  {
    [default] interface IClass1;
  };
};
