function tableout = imp_conc_out(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   IMPORTFILE(FILE) reads data from the first worksheet in the Microsoft
%   Excel spreadsheet file named FILE and returns the data as a table.
%
%   IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.
%
%	Date formatted cells are converted to MATLAB serial date number format
%	(datenum).
%   Non-numeric cells are replaced with: NaN
%
% Example:
%   importfile('concentrator_data.xlsx','Chemistry Data May-02 to
%   May-03',2,8400);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2013/12/10 14:43:03

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 8400;
end

%% Import the data, extracting spreadsheet dates in MATLAB serial date number format (datenum)
[~, ~, raw1, dateNums1] = xlsread(workbookFile, sheetName, sprintf('A%d:A%d',startRow(1),endRow(1)),'' , @convertSpreadsheetDates);
[~, ~, raw2, dateNums2] = xlsread(workbookFile, sheetName, sprintf('P%d:P%d',startRow(1),endRow(1)),'' , @convertSpreadsheetDates);
[~, ~, raw3, dateNums3] = xlsread(workbookFile, sheetName, sprintf('V%d:V%d',startRow(1),endRow(1)),'' , @convertSpreadsheetDates);
raw = [raw1,raw2,raw3];
dateNums = [dateNums1,dateNums2,dateNums3];
for block=2:length(startRow)
    [~, ~, tmpRawBlock1, tmpDateNumBlock1] = xlsread(workbookFile, sheetName, sprintf('A%d:A%d',startRow(block),endRow(block)),'' , @convertSpreadsheetDates);
    [~, ~, tmpRawBlock2, tmpDateNumBlock2] = xlsread(workbookFile, sheetName, sprintf('P%d:P%d',startRow(block),endRow(block)),'' , @convertSpreadsheetDates);
    [~, ~, tmpRawBlock3, tmpDateNumBlock3] = xlsread(workbookFile, sheetName, sprintf('V%d:V%d',startRow(block),endRow(block)),'' , @convertSpreadsheetDates);
    raw = [raw;tmpRawBlock1,tmpRawBlock2,tmpRawBlock3]; %#ok<AGROW>
    dateNums = [dateNums;tmpDateNumBlock1,tmpDateNumBlock2,tmpDateNumBlock3]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace date strings by MATLAB serial date numbers (datenum)
R = ~cellfun(@isequalwithequalnans,dateNums,raw) & cellfun('isclass',raw,'char'); % Find spreadsheet dates
raw(R) = dateNums(R);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
tableout = table;

%% Allocate imported array to column variable names
tableout.Time = data(:,1);
tableout.si = data(:,2);
tableout.mg = data(:,3);

