function createfigure2(X1, Y1, x2, ldc1)
%CREATEFIGURE2(X1, Y1, X2, LDC1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  LDC1:  vector of y data

%  Auto-generated by MATLAB on 31-Oct-2013 14:35:34

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XTickLabel',['01/06';'01/07';'01/08';'01/09';'01/10';'01/11'],...
    'XTick',[732678 733043 733408 733774 734139 734504],...
    'OuterPosition',[0 0.5 1 0.5]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[732678 734504]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'Color',[1 0 0]);

% Create axes
axes2 = axes('Parent',figure1,'OuterPosition',[0 0 1 0.5]);
box(axes2,'on');
hold(axes2,'all');

% Create plot
plot(x2,ldc1,'Parent',axes2,'DisplayName','ldc vs x');

