%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\AE\Load Forecasting AU\Load\ausdata.xlsx Worksheet:
%    Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2013/10/31 14:31:38

%% Import the data, extracting spreadsheet dates in MATLAB serial date number format (datenum)
[~, ~, raw, dateNums] = xlsread('C:\AE\Load Forecasting AU\Load\ausdata.xlsx','Sheet1','A2:H87649','',@convertSpreadsheetDates);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace date strings by MATLAB serial date numbers (datenum)
R = ~cellfun(@isequalwithequalnans,dateNums,raw) & cellfun('isclass',raw,'char'); % Find spreadsheet dates
raw(R) = dateNums(R);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Date1 = data(:,1);
Hour = data(:,2);
DryBulb = data(:,3);
DewPnt = data(:,4);
WetBulb = data(:,5);
Humidity = data(:,6);
ElecPrice = data(:,7);
SYSLoad = data(:,8);

%% Clear temporary variables
clearvars data raw dateNums R;